### ISSUE TITLE
[v0.4.1-0.19.1] Actions/h is NaN for actions limited by resource

### ISSUE THREAD

**Issue by SaladFork** [gmiclotte/melvor-scripts#12]
In `getXpRates`, the code initializes `rates` to an empty hash `{}` but then [tries to `+=` an undefined property on it](https://github.com/gmiclotte/melvor-scripts/blob/a540c/ETA/ETA.js#L1664). This results in it being NaN.

![image](https://user-images.githubusercontent.com/107798/112885088-4e6e0e00-909e-11eb-9678-466b9306ffab.png)

**Comment by gmiclotte** [comment]
Oops, forgot to test that for production skills. Fixed in 0.4.2, thanks a lot for reporting!
