### ISSUE TITLE
FireMonkey compatibility

### ISSUE THREAD

**Issue by gmiclotte** [gmiclotte/melvor-scripts#27]
> out of curiosity, how hard would it be to make your scripts use `@include`? They are incompatible with FireMonkey because it wants scripts to use either `@include` and `@exclude` OR `@match` and `@exclude-match`, and AFAICT TamperMonkey doesn't support `@exclude-match`. (It also needs `@inject-into page` but that's trivial)
I can easily change it myself and so could anyone else, of course (just two lines), so it's not a actual problem :)

**Comment by gmiclotte** [comment]
> btw FireMonkey's docs say: Due to matching order in Firefox/Chrome APIs, having mixed @match/@exclude-match with @include/@exclude/includeGlob/excludeGlob might have unexpected matched/unmatched results.
apparently that's why

**Comment by gmiclotte** [comment]
Should be fixed with 888da4f

**Comment by gmiclotte** [comment]
![2021-12-23_20-36](https://user-images.githubusercontent.com/12995926/147284956-cc175963-b9b1-4a10-a561-283caf0e6160.png)

**Comment by gmiclotte** [comment]
This should now be fixed

**Comment by erosman** [comment]
Just for info .... FireMonkey supports `include/exclude/match/exclude-match`
While all userscript managers support `include/exclude/match`, only FireMonkey & Violentmonkey supports `exclude-match`.

FireMonkey now auto-converts convertible `include/exclude` to `match/exclude-match`. In case of these, the original would work fine in FireMonkey (since they are all convertible to match pattern).
```
// @match        https://*.melvoridle.com/*
// @exclude      https://wiki.melvoridle.com/*
```

**Comment by gmiclotte** [comment]
Oh sweet, thanks for the information !

**Comment by erosman** [comment]
In case it is useful...

**Regarding script injection into `page` context** 
e.g.
```js
    const script = document.createElement('script');
    script.textContent = `try { (${main})(); } catch (e) { console.log(e); }`;
    document.body.appendChild(script).parentNode.removeChild(script);
```
- Greasemonkey is the only manager that doesn't have the option and needs manual injection as per above code
`GM.info.scriptHandler === 'Greasemonkey'` can be used. (All scripts always get GM.info even without specifically requesting it.)


Other managers can inject into `page` context so above is not needed and better avoided as it can cause the script to be injected twice.
- FireMonkey & Violentmonkey inject into `page` context when `@inject-into page`
- Tampermonkey injects into `page` context when `@grant        none`

**Comment by gmiclotte** [comment]
closing this since all user scripts are deprecated
