### ISSUE TITLE
[Melvor ETA] causes chrome tab to get unresponsive since Melvor 1.0.2

### ISSUE THREAD

**Issue by NobbZ** [gmiclotte/melvor-scripts#28]
Since last night I can not use Melvor ETA anymore, it brings the tab to 100% CPU and makes clicking anything impossible, even killing the tab through Chromes task manager takes a while, while I'm used to it beeing instant.

I can successfully select the character, then the page gets redrawn, and the "confirm AFK" dialog appears. This is when everything hangs. I am not able to confirm that dialog, nor clicking outside of it, only killing the tab helps.

I am also using the "Melvor Idle Combat Simulator Reloaded" to get the menu entry for configuration, not the tool itself. It doesn't make any difference whether this tool is activated or not, but I already realized if it is activated, its menu item is not available.

**Comment by gmiclotte** [comment]
ETA issues should be fixed in v0.9.0.

Combat simulator will be updated later today, and then the settings menu for ETA should work again.

Thanks
