### ISSUE TITLE
ETA firemaking, regardless of selected log type the per-hour stats is the same and "no ressources" shown

### ISSUE THREAD

**Issue by NobbZ** [gmiclotte/melvor-scripts#29]
With 0.9.0 I have the issue that there is basically no usable displayed data for firemaking.

Its stats do not change as I change different logs, and it always shows, that I had no ressources.

With 0.8.8 the info got at least updated properly after the first log got burned, though this isn't happening anymore with 0.9.0

**Comment by gmiclotte** [comment]
Should be fixed in ETA v0.9.1.

Thanks !
