### ISSUE TITLE
ETA: Calculations seem off for firemaking

### ISSUE THREAD

**Issue by NobbZ** [gmiclotte/melvor-scripts#30]
Yesterday I started firemaking, and the tooltip showed me, that I reach level 99 about two hours after getting up. I should have some spare logs left after that

When I started I had 8k to 10k yew logs IIRC.

Today I get up, and look at the progress and I see that not only I will not reach level 99 with my yews at all but require ~500 more of them, but also that burning all the logs I have now will take an additional ~90 minutes.

Despite the fact that I gained some mastery levels which should have sped up my burning rates. Sadly I do not remember yesterday evenings level anymore…

**Comment by gmiclotte** [comment]
closing this since ETA is being rewritten from scratch
