### ISSUE TITLE
Unlimited Offline: remove/edit the "18 Hours" message in the offline modal

### ISSUE THREAD

**Issue by Bersman** [gmiclotte/melvor-scripts#33]
I turned the unlimited mod on but I still got the text: 18 hours is the maximum offline progression.

Is this than a bug?
![SPOILER_unknown](https://user-images.githubusercontent.com/1538239/188920514-046c064c-d1fa-4baf-a988-9d64dddfe771.png)

**Comment by gmiclotte** [comment]
Hello

That line of text could indeed be removed by the Unlimited Offline mod, I'll add that to my todo list. But this should only be a visual issue, the full offline time is used for the computation.

Thanks!

**Comment by gmiclotte** [comment]
[fixed in v0.1.3 on mod.io](https://mod.io/g/melvoridle/m/unlimited-offline)
