### ISSUE TITLE
ETA: missing in Alt. magic.

### ISSUE THREAD

**Issue by hellofinch** [gmiclotte/melvor-scripts#36]
ETA is so good mod! I like it so much.
ETA in Alt. magic is missing. Is it right?
![image](https://github.com/gmiclotte/melvor-scripts/assets/42131198/fa4dafd0-71a2-4b78-b98e-69a6e9e0edfb)

**Comment by gmiclotte** [comment]
Hello

Thanks for reporting, that was definitely not normal. Should be fixed now in v1.1.1.
