### ISSUE TITLE
ETA: Mining/Woodcutting/Astrology ran out of iterations error

### ISSUE THREAD

**Issue by Voscor** [gmiclotte/melvor-scripts#38]
Hello

There's a slight issue with mining, woodcutting and astrology throwing up these errors for the new abyssal resources
Whenever you open the relevant skill, it shows these errors in the console which causes a stutter when recalculating after every refresh

![image_2024-06-13_174117005](https://github.com/gmiclotte/melvor-scripts/assets/46573917/e279b988-6e57-486c-8e19-1a00e348143e)
Attached example is for woodcutting trees but it's the same for new mining nodes and astrology constellations

Note: I haven't unlocked any of the abyssal stuff yet

**Comment by gmiclotte** [comment]
Hello

Thanks for reporting, this should be fixed in 1.1.4.

Archaeology is broken and might still throw this error though.

**Comment by gmiclotte** [comment]
Hello


Should be fixed for all skills in v1.1.5.

Thanks again!
