### ISSUE TITLE
ETA: not working for me anymore

### ISSUE THREAD

**Issue by Goten87** [gmiclotte/melvor-scripts#40]
hello i logged in sins a long time always used this plugin to see how long a craft was still going so i can login again when its done
but the compleet plugin broke for me i dont see any info anymore in the game did something change?

**Comment by gmiclotte** [comment]
Hello, please ensure you are using the latest version of the ETA mod (v1.1.44) through the mod manager. The mod should update automatically; if it hasn't, please check for updates manually.

If you’ve been away for a long time and missed the addition of official mod support, here’s what you need to do:
1. Create a mod.io account.
2. Link it to your Melvor account.
3. Subscribe to the mod: [https://mod.io/g/melvoridle/m/eta](https://mod.io/g/melvoridle/m/eta)
4. Enable the mod in the mod manager.

Hope that helps!

**Comment by Goten87** [comment]
ok i just did all this im on 1.1.44 and its still not showing up (is there something wrong if im max level in that skill)

i think thats it the skill i have is over max level so i cant see anymore how long it will take to burn true all the items i have
when i went to a skill without max level it shows again

**Comment by gmiclotte** [comment]
There was a bug with Alt. Magic, which has now been resolved. If that was the skill you are talking about, it should now show again in v1.1.45.

If the issue is with another skill, please specify, and provide a save link. Then I can have a look.

For the record, having the max level or not should not affect whether the ETA information shows up.

**Comment by Goten87** [comment]
yes that was the skill i had issues with and yes its fixed now thank you kind developer ^^
